
SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS;

-- BUSCANDO TODAS AS COLUNAS DA TABELA CLIENTES;
SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, 
VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO
FROM TB_CLIENTES;

-- BUSCANDO COLUNAS ESPECIFICAS;
SELECT CPF, NOME, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

-- BUSCANDO COLUNAS ESPECIFICAS;
SELECT IDADE, CPF, NOME, DATA_NASCIMENTO
FROM TB_CLIENTES;

-- BUSCANDO COLUNAS ESPECIFICAS, ALTERANDO O NOME DA COLUNA (CPF)
SELECT CPF AS CPF_DO_CLIENTE, NOME AS NOME_DO_CLIENTE, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

