-- selecionando todos os CAMPOS da tabela PRODUTO;
SELECT * FROM TB_PRODUTOS;

-- SELECIONANDO TODOS OS CAMPOS, (ONDE) [PRODUTO] É (IGUAL) A = ....
SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1037797';

-- SELECIONANDO TODOS OS CAMPOS, (ONDE) [CIDADE] É (IGUAL) A = ....
SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro';

-- SELECIONANDO TODOS OS CAMPOS, (ONDE) [SABOR] É (IGUAL) A = ....
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Laranja';

-- SELECIONANDO TODOS OS CAMPOS, (ONDE) [SABOR] É (IGUAL) A = ....
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

-- ATUALIZAR TABELA DE PRODUTOS, SELECIONANDO [SABOR] 
UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE PRODUTO = '1088126';
UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE PRODUTO = '544931';
UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE PRODUTO = '544931';

UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE SABOR = 'Limão';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Citricos';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

